name = "MPIParticleInCell"
uuid = "9ce4ebf3-bc69-4d54-a62a-99ca13ce92ee"
authors = ["Luke Adams <luke@lukeclydeadams.com> and contributors"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
MPI = "0.16, 0.17"
Primes = "0.5"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
